name: spellcheck

on:
  pull_request:
    branches: [ master ]
    paths:
    - '**.md'
    - '.wordlist.txt'
    - '.spellcheck.yaml'

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v2
    - name: Run PySpelling as a GitHub action
      uses: sbates130272/spellcheck-github-actions@v0.7.0
